### ISSUE TITLE
Consider Adding a Permissible Software License

### ISSUE THREAD

**Issue by emarinier** [katholt/sonneityping#6]
I've written a Galaxy wrapper for parse_mykrobe_predict.py, but it cannot be added to the [official tool shed](https://github.com/galaxyproject/tools-iuc) unless the software has a [permissible license](https://opensource.org/licenses/alphabetical) (as per the Galaxy tool shed [contribution requirements](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md#requirements-for-contributions)).

Please consider adding a permissible software license, as without such a license, [default copyright laws mostly apply](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository) (and nobody else can legally distribute the software).

**Comment by katholt** [comment]
A GNU license has now been added.
Please note new releases are reserved for updates to the genotyping scheme, so this will appear in the next release.

**Comment by emarinier** [comment]
Thank you!
